### ISSUE TITLE
Email generator required for the library

### ISSUE THREAD

**Issue by cnufed** [apptik/JustJson#5]
I think we need to add "email" formatter too. Currently, for string type it supports
is date-time format
is date format
is time format
is uri format

We should also add "email" format.

**Comment by djodjoni** [comment]
yep this is nice to add. I am quite busy right now so i will not be evolving much the json-schema related stuff any time soon. However feel free to make a PR :)

**Comment by cnufed** [comment]
PR it is:
https://github.com/apptik/JustJson/pull/6
